<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>  
	<?php
		echo $this->headMeta()
		->setHttpEquiv('Content-Type', 'text/html; charset=UTF-8')
		->setHttpEquiv('Content-Style-Type', 'text/css')
		->setHttpEquiv('lang', 'fr' )
		->setName('author', 'Nittel Romain')
		->setName('language', 'fr');
	?>
 	<?php echo $this->headTitle('Paniers de la ferme'); ?>
  	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
	<!-- Bootstrap -->
	<link href="<?php echo $this->baseUrl();?>/backend/css/bootstrap/bootstrap.min.css" rel="stylesheet">
	<!-- Font Awesome -->
	<link href="<?php echo $this->baseUrl();?>/backend/font-awesome/css/font-awesome.min.css" rel="stylesheet">
	<!-- NProgress -->
	<link href="<?php echo $this->baseUrl();?>/backend/css/nprogress/nprogress.css" rel="stylesheet">
	<!-- Animate.css -->
	<link href="<?php echo $this->baseUrl();?>/backend/css/animate/animate.min.css" rel="stylesheet">
	<!-- Custom Theme Style -->
	<link href="<?php echo $this->baseUrl();?>/backend/css/custom.min.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl();?>/backend/css/theme.css" rel="stylesheet">
</head>
<body class="login">
	<div>
		<a class="hiddenanchor" id="signup"></a> <a class="hiddenanchor" id="signin"></a>
		<div class="login_wrapper">
			<div class="animate form login_form">
				<section class="login_content">
					<?php echo $this->layout()->content?>
				</section>
			</div>
		</div>
	</div>
</body>
</html>